# Generated by Django 5.2 on 2025-04-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('A', 'A+'), ('A−', 'A−'), ('B+', 'B+'), ('B−', 'B−'), ('AB+', 'AB+'), ('AB−', 'AB−'), ('O+', 'O+'), ('O−', 'O−')], max_length=3),
        ),
        migrations.AlterField(
            model_name='donor',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
