# Generated by Django 5.2 on 2025-04-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_alter_donor_blood_group_alter_donor_contact_number'),
        ('blood', '0003_loginform_username'),
    ]

    operations = [
    ]
